# Generated by Django 2.2.6 on 2019-12-08 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MainTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NLecii', models.CharField(max_length=250)),
                ('Predmet', models.CharField(max_length=250)),
                ('Prepod', models.CharField(max_length=250)),
                ('Podgruppa', models.CharField(max_length=250)),
                ('vremya', models.DateTimeField()),
                ('Auditoriya', models.CharField(max_length=250)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='draft', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Prepod1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('LessonNumber', models.IntegerField(null=True)),
                ('Date', models.DateField(null=True)),
                ('isBusy', models.BooleanField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='studyPlanPE61',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=250)),
                ('typeSubject', models.CharField(max_length=50)),
                ('hours', models.IntegerField()),
                ('teacher', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='studyPlanPE71',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=250)),
                ('typeSubject', models.CharField(max_length=50)),
                ('hours', models.IntegerField()),
                ('teacher', models.CharField(max_length=150)),
            ],
        ),
    ]
