# Generated by Django 3.0.3 on 2020-02-23 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teacher2',
            old_name='teache',
            new_name='teacher',
        ),
    ]
