# Generated by Django 3.0.4 on 2020-03-21 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0002_auto_20200223_1232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maintable',
            name='vremya',
            field=models.DateTimeField(null=True),
        ),
    ]
