# Generated by Django 2.2.6 on 2019-12-08 08:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0002_prepod2'),
    ]

    operations = [
        migrations.DeleteModel(
            name='studyPlanPE61',
        ),
        migrations.DeleteModel(
            name='studyPlanPE71',
        ),
    ]
