# Generated by Django 3.0.5 on 2020-05-05 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0002_auto_20200503_1943'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher1',
            name='isBusy',
        ),
    ]
