# Generated by Django 3.0.4 on 2020-03-21 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0003_auto_20200321_1455'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maintable',
            name='vremya',
            field=models.DateTimeField(default=None),
        ),
    ]
