# Generated by Django 3.0.5 on 2020-05-05 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0003_remove_teacher1_isbusy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maintable',
            name='vremya',
            field=models.DateField(),
        ),
    ]
