# Generated by Django 2.2.6 on 2019-12-08 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0003_auto_20191208_1306'),
    ]

    operations = [
        migrations.CreateModel(
            name='studyPlanPE61',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=250)),
                ('typeSubject', models.CharField(max_length=50)),
                ('hours', models.IntegerField()),
                ('teacher', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='studyPlanPE71',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=250)),
                ('typeSubject', models.CharField(max_length=50)),
                ('hours', models.IntegerField()),
                ('teacher', models.CharField(max_length=150)),
            ],
        ),
    ]
