# Generated by Django 3.0.5 on 2020-05-05 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0005_auto_20200505_1412'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher2',
            name='isBusy',
        ),
        migrations.RemoveField(
            model_name='teacher3',
            name='isBusy',
        ),
        migrations.RemoveField(
            model_name='teacher4',
            name='isBusy',
        ),
        migrations.RemoveField(
            model_name='teacher5',
            name='isBusy',
        ),
        migrations.AlterField(
            model_name='maintable',
            name='NLecii',
            field=models.IntegerField(null=True),
        ),
    ]
