# Generated by Django 2.2.6 on 2019-12-08 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0005_auto_20191208_1339'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studyplanpe61',
            name='hours',
            field=models.IntegerField(),
        ),
    ]
