# Generated by Django 3.0.5 on 2020-05-05 15:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('MainApp', '0006_auto_20200505_1417'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='maintable',
            name='status',
        ),
        migrations.CreateModel(
            name='studyPlanGroup2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=250)),
                ('typeSubject', models.CharField(max_length=50)),
                ('hours', models.IntegerField()),
                ('remaningLectures', models.IntegerField()),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MainTableGroup2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NLecii', models.IntegerField(null=True)),
                ('Predmet', models.CharField(max_length=250, null=True)),
                ('Prepod', models.CharField(max_length=250, null=True)),
                ('Podgruppa', models.CharField(max_length=250, null=True)),
                ('vremya', models.DateField()),
                ('Auditoriya', models.CharField(max_length=250, null=True)),
                ('teacherId', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
