# Generated by Django 3.0.4 on 2020-03-21 12:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0006_auto_20200321_1509'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maintable',
            name='Auditoriya',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='maintable',
            name='NLecii',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='maintable',
            name='Podgruppa',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='maintable',
            name='Predmet',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='maintable',
            name='Prepod',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='maintable',
            name='vremya',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 21, 15, 18, 56, 154415)),
        ),
    ]
