# Generated by Django 3.0.4 on 2020-03-21 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0008_auto_20200321_1523'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maintable',
            name='Auditoriya',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='maintable',
            name='NLecii',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='maintable',
            name='Podgruppa',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='maintable',
            name='Predmet',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='maintable',
            name='Prepod',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
