# Generated by Django 3.0.4 on 2020-03-22 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0010_customvalues'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customvalues',
            old_name='Value',
            new_name='value',
        ),
    ]
