# Generated by Django 3.0.4 on 2020-03-22 16:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('MainApp', '0011_auto_20200322_1924'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintable',
            name='teacherId',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
