# Generated by Django 3.0.4 on 2020-03-22 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0012_maintable_teacherid'),
    ]

    operations = [
        migrations.AddField(
            model_name='studyplanpe61',
            name='remaningLectures',
            field=models.CharField(default=models.IntegerField(), max_length=250),
        ),
    ]
