# Generated by Django 3.0.4 on 2020-03-22 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0013_studyplanpe61_remaninglectures'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studyplanpe61',
            name='remaningLectures',
            field=models.CharField(default=0, max_length=250),
        ),
    ]
