# Generated by Django 3.0.4 on 2020-03-23 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0014_auto_20200322_2103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studyplanpe61',
            name='remaningLectures',
            field=models.IntegerField(),
        ),
    ]
